### ISSUE TITLE
Extract Kotlin runtime and stdlib versions to kotlin.version property

### ISSUE THREAD

**Issue by gvlasov** [mhshams/kotlin-quickstart-archetype#2]
It would be convenient if the version of Kotlin was defined by a property. 

Also, isn't it high time to bump up the version used in the archetype up to the latest 1.0.0-beta-1103?

**Comment by mhshams** [comment]
@Suseika the **kotlinVersion** is defined as parameter and you can specify it during the build (check the README page and let me know if that is not exactly what you want). 

I would bump the version soon, although I don't think it is not that necessary.

**Comment by gvlasov** [comment]
@mhshams It would be better to have a property defined in `pom.xml` simply from the DRY perspective: a version is defined in two places (for artifacts `kotlin-stdlib` and `kotlin-maven-plugin`), it would be better if it was defined in one place and reused twice, because in most cases you would want these artifacts to be of the same version.

**Comment by mhshams** [comment]
@Suseika  thanks for the clarification, both issues are fixed now. 

I will release the artifact and it would be available in new few ours in the maven central

**Comment by gvlasov** [comment]
@mhshams Thank you very much!
